---------------------
DROP TABLE IF EXISTS [NAO_PMO_Analytics].[dbo].zzz_mithun_forecast01;  

SELECT   CONVERT([Date], date) as Date
      ,[Scenario]
      ,[Product]
      ,[Sub-Product]
      , try_convert(bigint,[Actual Volumes]) as m_Volumes
      , try_convert(float,[AutoRegressive_m]) as m_AutoRegressive_m
      , try_convert(float,[MovingAverage_m]) as m_MovingAverage
      , try_convert(float,[AutoRegressive_MovingAverage_m]) as m_AutoRegressive_MovingAverage
      , try_convert(float,[AutoRegressive_Integrated_MovingAverage_m]) as m_AutoRegressive_Integrated_MovingAverage
      , try_convert(float,[Seasonal_AutoRegressive_Integrated_MovingAverage_m1]) as m1_Seasonal_AutoRegressive_Integrated_MovingAverage
      , try_convert(float,[Seasonal_AutoRegressive_Integrated_MovingAverage_m2]) as m2_Seasonal_AutoRegressive_Integrated_MovingAverage
      , try_convert(float,[Seasonal_AutoRegressive_Integrated_MovingAverage_m3]) as m3_Seasonal_AutoRegressive_Integrated_MovingAverage
      , try_convert(float,[Seasonal_AutoRegressive_Integrated_MovingAverage_m4]) as m4_Seasonal_AutoRegressive_Integrated_MovingAverage
      , try_convert(float,[Seasonal_AutoRegressive_Integrated_MovingAverage_m5]) as m5_Seasonal_AutoRegressive_Integrated_MovingAverage
      , try_convert(float,[Holts_added_linear_trend_m]) as m_Holts_added_linear_trend
      , try_convert(float,[Holts_added_damped_linear_trend_m]) as m_Holts_added_damped_linear_trend
      , try_convert(float,[Holts_multiplicative_linear_trend_m]) as m1_Holts_multiplicative_linear_trend
      , try_convert(float,[Holts_multiplicative_damped_linear_trend_m]) as m2_Holts_multiplicative_damped_linear_trend
      , try_convert(float,[Holts_added_linear_trend_with_seasonality_m]) as m3_Holts_added_linear_trend_with_seasonality
      , try_convert(float,[Holts_added_dampened_linear_trend_with_seasonality_m]) as m_Holts_added_dampened_linear_trend_with_seasonality
      , try_convert(float,[Holts_multiplicative_linear_trend_with_seasonality_m]) as m_Holts_multiplicative_linear_trend_with_seasonality
      , try_convert(float,[Holts_multiplicative_dampened_linear_trend_with_seasonality_m]) as m_Holts_multiplicative_dampened_linear_trend_with_seasonality
      , try_convert(float,[Holts_tunned_model_m1]) as m1_Holts_tunned_model_m1
      , try_convert(float,[Holts_tunned_model_m2]) as m2_Holts_tunned_model_m1
      , try_convert(float,[Holts_tunned_model_m3]) as m3_Holts_tunned_model_m1
      , try_convert(float,[Simple_Exponential_Smoothing_m]) as m_Simple_Exponential_Smoothing_m
      , try_convert(float,[Error_trend_seasonality_tunned_m1]) as m1_Error_trend_seasonality_tunned
      , try_convert(float,[Error_trend_seasonality_tunned_m2])as m2_Error_trend_seasonality_tunned
      , try_convert(float,[Error_trend_seasonality_tunned_m3])as m3_Error_trend_seasonality_tunned
      , try_convert(float,[NeuralNetwork_1m]) as m1_NN
      , try_convert(float,[LongShort_termMemory_1m]) as m1_LSTM
      , try_convert(float,[NeuralNetwork_2m])as m2_NN
      , try_convert(float,[ConvolutionalNeuralNetwork_2m]) as m2_CNN
      , try_convert(float,[LongShort_termMemory_2m]) as m2_LSTM
      , try_convert(float,[NeuralNetwork_3m])as m3_NN
      , try_convert(float,[ConvolutionalNeuralNetwork_3m]) as m3_CNN
      , try_convert(float,[LongShort_termMemory_3m]) as m3_LSTM
      , try_convert(float,[NeuralNetwork_4m]) as m4_NN
      , try_convert(float,[ConvolutionalNeuralNetwork_4m])as m4_CNN
      , try_convert(float,[LongShort_termMemory_4m])as m4_LSTM
      , try_convert(float,[ConvolutionalNeuralNetwork_LongShort_termMemory_4m])as m4_LSTM_CNN
      , try_convert(float,[Prophet]) as m_Prophet
      , try_convert(float,[GPy]) as m_GPY
      , try_convert(float,[Decision_tree]) as m_Regression_Tree
      , try_convert(float,[Random_forest]) as m_Random_forest
	  into [NAO_PMO_Analytics].[dbo].zzz_mithun_forecast01
  FROM [NAO_PMO_Analytics].[dbo].[zzz_mithun_juptest];
  
  
  
DROP TABLE IF EXISTS [NAO_PMO_Analytics].[dbo].zzz_chris_final01;

SELECT 
      convert([Date], date) as Date
      ,[Scenario]
      ,[Product]
      ,[Sub.Product]
      ,convert(bigint,[Volumes]) as Volumes
      ,convert(float,c1_AAA_ets) as c1_AAA_ets
	  ,convert(float,[c1_AAN_ets]) as [c1_AAN_ets]
	   ,convert(float,[c1_add_holtlineartrend]) as [c1_add_holtlineartrend]
	   ,convert(float,[c1_add_holtlineartrenddamp]) as [c1_add_holtlineartrenddamp]
	   ,convert(float,[c1_ANA_ets]) as [c1_ANA_ets]
	   ,convert(float,[c1_autoregressive_integratedmovingaverage]) as [c1_autoregressive_integratedmovingaverage]
       ,convert(float,[c1_autoregressive_integratedmovingaverage_1]) as [c1_autoregressive_integratedmovingaverage_1]
      ,convert(float,[c1_autoregressive_integratedmovingaverage_2]) as [c1_autoregressive_integratedmovingaverage_2]
	   ,convert(float,[c1_autoregressive_integratedmovingaverage_3]) as [c1_autoregressive_integratedmovingaverage_3]
	    ,convert(float,[c1_autoregressive_integratedmovingaverage_4]) as [c1_autoregressive_integratedmovingaverage_4]
		 ,convert(float,[c1_autoregressive_integratedmovingaverage_5]) as [c1_autoregressive_integratedmovingaverage_5]
		  ,convert(float,[c1_boxcoxtransform_armaerrors_trend_seasonal]) as [c1_boxcoxtransform_armaerrors_trend_seasonal]
		   ,convert(float,[c1_cubicspline1]) as [c1_cubicspline1]
		    ,convert(float,[c1_cubicspline2]) as [c1_cubicspline2]
      		    ,convert(float,[c1_double_holt_additive]) as [c1_double_holt_additive]
      		    ,convert(float,[c1_dynamicharmonicregression]) as [c1_dynamicharmonicregression]
      		    ,convert(float,[c1_linearmodel_seasontrend]) as [c1_linearmodel_seasontrend]
      		    ,convert(float,[c1_linearmodel_trend]) as [c1_linearmodel_trend]
      		    ,convert(float,[c1_MAA_ets]) as [c1_MAA_ets]
      		    ,convert(float,[c1_MAM_ets]) as [c1_MAM_ets]
      		    ,convert(float,[c1_MAN_ets]) as [c1_MAN_ets]
      		    ,convert(float,[c1_MMM_ets]) as [c1_MMM_ets]
      		    ,convert(float,[c1_MMN_ets]) as [c1_MMN_ets]
      		    ,convert(float,[c1_MNA_ets]) as [c1_MNA_ets]
      		    ,convert(float,[c1_MNM_ets]) as [c1_MNM_ets]
      		    ,convert(float,[c1_sarima1]) as [c1_sarima1]
      		    ,convert(float,[c1_sarima10]) as [c1_sarima10]
      		    ,convert(float,[c1_sarima11]) as [c1_sarima11]
      		    ,convert(float,[c1_sarima12]) as [c1_sarima12]
                ,convert(float,[c1_sarima13]) as [c1_sarima13]
				,convert(float,[c1_sarima14]) as [c1_sarima14]
			   ,convert(float,[c1_sarima15]) as [c1_sarima15]
			   ,convert(float,[c1_sarima16]) as [c1_sarima16]
			   ,convert(float,[c1_sarima17]) as [c1_sarima17]
			   ,convert(float,[c1_sarima18]) as [c1_sarima18]
			   		  ,convert(float,[c1_sarima19]) as [c1_sarima19]
			   		  ,convert(float,[c1_sarima2]) as [c1_sarima2]
			   		  ,convert(float,[c1_sarima20]) as [c1_sarima20]
			   		  ,convert(float,[c1_sarima21]) as [c1_sarima21]
					  ,convert(float,[c1_sarima22]) as [c1_sarima22]
 					  ,convert(float,[c1_sarima23]) as [c1_sarima23]
     					  ,convert(float,[c1_sarima24]) as [c1_sarima24]
      					  ,convert(float,[c1_sarima25]) as [c1_sarima25]
      					  ,convert(float,[c1_sarima26]) as [c1_sarima26]
      					  ,convert(float,[c1_sarima27]) as [c1_sarima27]
      					  ,convert(float,[c1_sarima28]) as [c1_sarima28]
      					  ,convert(float,[c1_sarima29]) as [c1_sarima29]
      					  ,convert(float,[c1_sarima3]) as [c1_sarima3]
      					  ,convert(float,[c1_sarima30]) as [c1_sarima30]
      					  ,convert(float,[c1_sarima31]) as [c1_sarima31]
      					  ,convert(float,[c1_sarima32]) as [c1_sarima32]
      					  ,convert(float,[c1_sarima33]) as [c1_sarima33]
      					  ,convert(float,[c1_sarima34]) as [c1_sarima34]
      					  ,convert(float,[c1_sarima35]) as [c1_sarima35]
      					  ,convert(float,[c1_sarima36]) as [c1_sarima36]
      					  ,convert(float,[c1_sarima37]) as [c1_sarima37]
      					  ,convert(float,[c1_sarima38]) as [c1_sarima38]
      					  ,convert(float,[c1_sarima39]) as [c1_sarima39]
      					  ,convert(float,[c1_sarima4]) as [c1_sarima4]
      					  ,convert(float,[c1_sarima40]) as [c1_sarima40]
      					  ,convert(float,[c1_sarima41]) as [c1_sarima41]
      					  ,convert(float,[c1_sarima42]) as [c1_sarima42]
      					  ,convert(float,[c1_sarima43]) as [c1_sarima43]
      					  ,convert(float,[c1_sarima44]) as [c1_sarima44]
      					  ,convert(float,[c1_sarima45]) as [c1_sarima45]
      					  ,convert(float,[c1_sarima46]) as [c1_sarima46]
						    ,convert(float,[c1_sarima47]) as [c1_sarima47]
      					  ,convert(float,[c1_sarima48]) as [c1_sarima48]
      					  ,convert(float,[c1_sarima49]) as [c1_sarima49]
      					  ,convert(float,[c1_sarima5]) as [c1_sarima5]
      					  ,convert(float,[c1_sarima50]) as [c1_sarima50]
      					  ,convert(float,[c1_sarima51]) as [c1_sarima51]
      					  ,convert(float,[c1_sarima52]) as [c1_sarima52]
      					  ,convert(float,[c1_sarima53]) as [c1_sarima53]
						  ,convert(float,[c1_sarima54]) as [c1_sarima54]
						  ,convert(float,[c1_sarima55]) as [c1_sarima55]
						  ,convert(float,[c1_sarima56]) as [c1_sarima56]
						  ,convert(float,[c1_sarima57]) as [c1_sarima57]
						  ,convert(float,[c1_sarima58]) as [c1_sarima58]
						  ,convert(float,[c1_sarima59]) as [c1_sarima59]
						  ,convert(float,[c1_sarima6]) as [c1_sarima6]
						  ,convert(float,[c1_sarima60]) as [c1_sarima60]
						  ,convert(float,[c1_sarima61]) as [c1_sarima61]
						   ,convert(float,[c1_sarima62]) as [c1_sarima62]
						  ,convert(float,[c1_sarima63]) as [c1_sarima63]
						  ,convert(float,[c1_sarima64]) as [c1_sarima64]
						   ,convert(float,[c1_sarima65]) as [c1_sarima65]
						    ,convert(float,[c1_sarima66]) as [c1_sarima66]
							 ,convert(float,[c1_sarima67]) as [c1_sarima67]
							  ,convert(float,[c1_sarima68]) as [c1_sarima68]
							  ,convert(float,[c1_sarima69]) as [c1_sarima69]
							  ,convert(float,[c1_sarima7]) as [c1_sarima7]
							  ,convert(float,[c1_sarima70]) as [c1_sarima70]
							  ,convert(float,[c1_sarima71]) as [c1_sarima71]
							  ,convert(float,[c1_sarima72]) as [c1_sarima72]
							  ,convert(float,[c1_sarima73]) as [c1_sarima73]
							  ,convert(float,[c1_sarima74]) as [c1_sarima74]
							  ,convert(float,[c1_sarima75]) as [c1_sarima75]
							    ,convert(float,[c1_sarima76]) as [c1_sarima76]
							  ,convert(float,[c1_sarima77]) as [c1_sarima77]
							  ,convert(float,[c1_sarima8]) as [c1_sarima8]
							    ,convert(float,[c1_sarima9]) as [c1_sarima9]
    							  ,convert(float,[c1_simple_expo_smooth0]) as [c1_simple_expo_smooth0]
    							  --,convert(float,[c1_triple_holtwinters_additive0]) as [c1_triple_holtwinters_additive0]
    							  ,convert(float,[c1_triple_holtwinters_additive1]) as [c1_triple_holtwinters_additive1]
    							  ,convert(float,[c1_triple_holtwinters_additive10]) as [c1_triple_holtwinters_additive10]
        							  ,convert(float,[c1_triple_holtwinters_additive100]) as [c1_triple_holtwinters_additive100]
    							  ,convert(float,[c1_triple_holtwinters_additive11]) as [c1_triple_holtwinters_additive11]
    							  ,convert(float,[c1_triple_holtwinters_additive12]) as [c1_triple_holtwinters_additive12]
    							  ,convert(float,[c1_triple_holtwinters_additive13]) as [c1_triple_holtwinters_additive13]
    							  ,convert(float,[c1_triple_holtwinters_additive14]) as [c1_triple_holtwinters_additive14]
    							  ,convert(float,[c1_triple_holtwinters_additive15]) as [c1_triple_holtwinters_additive15]
    							  ,convert(float,[c1_triple_holtwinters_additive16]) as [c1_triple_holtwinters_additive16]
    							  ,convert(float,[c1_triple_holtwinters_additive17]) as [c1_triple_holtwinters_additive17]
    							  ,convert(float,[c1_triple_holtwinters_additive18]) as [c1_triple_holtwinters_additive18]
    							  ,convert(float,[c1_triple_holtwinters_additive19]) as [c1_triple_holtwinters_additive19]
    							  ,convert(float,[c1_triple_holtwinters_additive2]) as [c1_triple_holtwinters_additive2]
								   ,convert(float,[c1_triple_holtwinters_additive20]) as [c1_triple_holtwinters_additive20]
								   ,convert(float,[c1_triple_holtwinters_additive21]) as [c1_triple_holtwinters_additive21]
								   ,convert(float,[c1_triple_holtwinters_additive22]) as [c1_triple_holtwinters_additive22]
								   ,convert(float,[c1_triple_holtwinters_additive23]) as [c1_triple_holtwinters_additive23]
								   ,convert(float,[c1_triple_holtwinters_additive24]) as [c1_triple_holtwinters_additive24]
								   ,convert(float,[c1_triple_holtwinters_additive25]) as [c1_triple_holtwinters_additive25]
								   ,convert(float,[c1_triple_holtwinters_additive26]) as [c1_triple_holtwinters_additive26]
								   ,convert(float,[c1_triple_holtwinters_additive27]) as [c1_triple_holtwinters_additive27]
								   ,convert(float,[c1_triple_holtwinters_additive28]) as [c1_triple_holtwinters_additive28]
								   ,convert(float,[c1_triple_holtwinters_additive29]) as [c1_triple_holtwinters_additive29]
								   ,convert(float,[c1_triple_holtwinters_additive3]) as [c1_triple_holtwinters_additive3]
								   ,convert(float,[c1_triple_holtwinters_additive30]) as [c1_triple_holtwinters_additive30]
								   ,convert(float,[c1_triple_holtwinters_additive31]) as [c1_triple_holtwinters_additive31]
								   ,convert(float,[c1_triple_holtwinters_additive32]) as [c1_triple_holtwinters_additive32]
								   ,convert(float,[c1_triple_holtwinters_additive33]) as [c1_triple_holtwinters_additive33]
								   ,convert(float,[c1_triple_holtwinters_additive34]) as [c1_triple_holtwinters_additive34]
								   ,convert(float,[c1_triple_holtwinters_additive35]) as [c1_triple_holtwinters_additive35]
								      ,convert(float,[c1_triple_holtwinters_additive36]) as [c1_triple_holtwinters_additive36]
								   ,convert(float,[c1_triple_holtwinters_additive37]) as [c1_triple_holtwinters_additive37]
								   ,convert(float,[c1_triple_holtwinters_additive38]) as [c1_triple_holtwinters_additive38]
								   ,convert(float,[c1_triple_holtwinters_additive39]) as [c1_triple_holtwinters_additive39]
								   ,convert(float,[c1_triple_holtwinters_additive4]) as [c1_triple_holtwinters_additive4]
								   ,convert(float,[c1_triple_holtwinters_additive40]) as [c1_triple_holtwinters_additive40]
								   ,convert(float,[c1_triple_holtwinters_additive41]) as [c1_triple_holtwinters_additive41]
								   ,convert(float,[c1_triple_holtwinters_additive42]) as [c1_triple_holtwinters_additive42]
								   ,convert(float,[c1_triple_holtwinters_additive43]) as [c1_triple_holtwinters_additive43]
								      ,convert(float,[c1_triple_holtwinters_additive44]) as [c1_triple_holtwinters_additive44]
								   ,convert(float,[c1_triple_holtwinters_additive45]) as [c1_triple_holtwinters_additive45]
								   ,convert(float,[c1_triple_holtwinters_additive46]) as [c1_triple_holtwinters_additive46]
        ,convert(float,[c1_triple_holtwinters_additive47]) as [c1_triple_holtwinters_additive47]
		   ,convert(float,[c1_triple_holtwinters_additive48]) as [c1_triple_holtwinters_additive48]
		      ,convert(float,[c1_triple_holtwinters_additive49]) as [c1_triple_holtwinters_additive49]
			     ,convert(float,[c1_triple_holtwinters_additive5]) as [c1_triple_holtwinters_additive5]
				    ,convert(float,[c1_triple_holtwinters_additive50]) as [c1_triple_holtwinters_additive50]
					   ,convert(float,[c1_triple_holtwinters_additive51]) as [c1_triple_holtwinters_additive51]
					      ,convert(float,[c1_triple_holtwinters_additive52]) as [c1_triple_holtwinters_additive52]
						     ,convert(float,[c1_triple_holtwinters_additive53]) as [c1_triple_holtwinters_additive53]
							    ,convert(float,[c1_triple_holtwinters_additive54]) as [c1_triple_holtwinters_additive54]
								   ,convert(float,[c1_triple_holtwinters_additive55]) as [c1_triple_holtwinters_additive55]
								      ,convert(float,[c1_triple_holtwinters_additive56]) as [c1_triple_holtwinters_additive56]
    								      ,convert(float,[c1_triple_holtwinters_additive57]) as [c1_triple_holtwinters_additive57]
								      ,convert(float,[c1_triple_holtwinters_additive58]) as [c1_triple_holtwinters_additive58]
								      ,convert(float,[c1_triple_holtwinters_additive59]) as [c1_triple_holtwinters_additive59]
									  ,convert(float,[c1_triple_holtwinters_additive6]) as [c1_triple_holtwinters_additive6]
								      ,convert(float,[c1_triple_holtwinters_additive60]) as [c1_triple_holtwinters_additive60]
									  ,convert(float,[c1_triple_holtwinters_additive61]) as [c1_triple_holtwinters_additive61]
								      ,convert(float,[c1_triple_holtwinters_additive62]) as [c1_triple_holtwinters_additive62]
									 ,convert(float,[c1_triple_holtwinters_additive63]) as [c1_triple_holtwinters_additive63]
									 ,convert(float,[c1_triple_holtwinters_additive64]) as [c1_triple_holtwinters_additive64]
									 ,convert(float,[c1_triple_holtwinters_additive65]) as [c1_triple_holtwinters_additive65]
									 ,convert(float,[c1_triple_holtwinters_additive66]) as [c1_triple_holtwinters_additive66]
									 ,convert(float,[c1_triple_holtwinters_additive67]) as [c1_triple_holtwinters_additive67]
									 ,convert(float,[c1_triple_holtwinters_additive68]) as [c1_triple_holtwinters_additive68]
									 ,convert(float,[c1_triple_holtwinters_additive69]) as [c1_triple_holtwinters_additive69]
									  ,convert(float,[c1_triple_holtwinters_additive7]) as [c1_triple_holtwinters_additive7]
									   ,convert(float,[c1_triple_holtwinters_additive70]) as [c1_triple_holtwinters_additive70]
									    ,convert(float,[c1_triple_holtwinters_additive71]) as [c1_triple_holtwinters_additive71]
										,convert(float,[c1_triple_holtwinters_additive72]) as [c1_triple_holtwinters_additive72]
										,convert(float,[c1_triple_holtwinters_additive73]) as [c1_triple_holtwinters_additive73]
										,convert(float,[c1_triple_holtwinters_additive74]) as [c1_triple_holtwinters_additive74]
										,convert(float,[c1_triple_holtwinters_additive75]) as [c1_triple_holtwinters_additive75]
										,convert(float,[c1_triple_holtwinters_additive76]) as [c1_triple_holtwinters_additive76]
										 ,convert(float,[c1_triple_holtwinters_additive77]) as [c1_triple_holtwinters_additive77]
									   ,convert(float,[c1_triple_holtwinters_additive78]) as [c1_triple_holtwinters_additive78]
									    ,convert(float,[c1_triple_holtwinters_additive79]) as [c1_triple_holtwinters_additive79]
										,convert(float,[c1_triple_holtwinters_additive8]) as [c1_triple_holtwinters_additive8]
										,convert(float,[c1_triple_holtwinters_additive80]) as [c1_triple_holtwinters_additive80]
										,convert(float,[c1_triple_holtwinters_additive81]) as [c1_triple_holtwinters_additive81]
										,convert(float,[c1_triple_holtwinters_additive82]) as [c1_triple_holtwinters_additive82]
										,convert(float,[c1_triple_holtwinters_additive83]) as [c1_triple_holtwinters_additive83]	
										,convert(float,[c1_triple_holtwinters_additive84]) as [c1_triple_holtwinters_additive84]
										 ,convert(float,[c1_triple_holtwinters_additive85]) as [c1_triple_holtwinters_additive85]
										,convert(float,[c1_triple_holtwinters_additive86]) as [c1_triple_holtwinters_additive86]
										,convert(float,[c1_triple_holtwinters_additive87]) as [c1_triple_holtwinters_additive87]
										,convert(float,[c1_triple_holtwinters_additive88]) as [c1_triple_holtwinters_additive88]
										,convert(float,[c1_triple_holtwinters_additive89]) as [c1_triple_holtwinters_additive89]
										,convert(float,[c1_triple_holtwinters_additive9]) as [c1_triple_holtwinters_additive9]	
										,convert(float,[c1_triple_holtwinters_additive90]) as [c1_triple_holtwinters_additive90]
										 ,convert(float,[c1_triple_holtwinters_additive91]) as [c1_triple_holtwinters_additive91]
										,convert(float,[c1_triple_holtwinters_additive92]) as [c1_triple_holtwinters_additive92]
										,convert(float,[c1_triple_holtwinters_additive93]) as [c1_triple_holtwinters_additive93]
										,convert(float,[c1_triple_holtwinters_additive94]) as [c1_triple_holtwinters_additive94]
										,convert(float,[c1_triple_holtwinters_additive95]) as [c1_triple_holtwinters_additive95]
										,convert(float,[c1_triple_holtwinters_additive96]) as [c1_triple_holtwinters_additive96]	
										,convert(float,[c1_triple_holtwinters_additive97]) as [c1_triple_holtwinters_additive97]
										,convert(float,[c1_triple_holtwinters_additive98]) as [c1_triple_holtwinters_additive98]
										,convert(float,[c1_triple_holtwinters_additive99]) as [c1_triple_holtwinters_additive99]
										,convert(float,[c1_triple_holtwinters_multiplicative0]) as [c1_triple_holtwinters_multiplicative0]
										,convert(float,[c1_triple_holtwinters_multiplicative1]) as [c1_triple_holtwinters_multiplicative1]
										,convert(float,[c1_triple_holtwinters_multiplicative10]) as [c1_triple_holtwinters_multiplicative10]	
										,convert(float,[c1_triple_holtwinters_multiplicative100]) as [c1_triple_holtwinters_multiplicative100]
									    ,convert(float,[c1_triple_holtwinters_multiplicative11]) as [c1_triple_holtwinters_multiplicative11]
										,convert(float,[c1_triple_holtwinters_multiplicative12]) as [c1_triple_holtwinters_multiplicative12]
										,convert(float,[c1_triple_holtwinters_multiplicative13]) as [c1_triple_holtwinters_multiplicative13]
										,convert(float,[c1_triple_holtwinters_multiplicative14]) as [c1_triple_holtwinters_multiplicative14]
										,convert(float,[c1_triple_holtwinters_multiplicative15]) as [c1_triple_holtwinters_multiplicative15]
										,convert(float,[c1_triple_holtwinters_multiplicative16]) as [c1_triple_holtwinters_multiplicative16]
										,convert(float,[c1_triple_holtwinters_multiplicative17]) as [c1_triple_holtwinters_multiplicative17]
										,convert(float,[c1_triple_holtwinters_multiplicative18]) as [c1_triple_holtwinters_multiplicative18]
										,convert(float,[c1_triple_holtwinters_multiplicative19]) as [c1_triple_holtwinters_multiplicative19]
										,convert(float,[c1_triple_holtwinters_multiplicative2]) as [c1_triple_holtwinters_multiplicative2]
										,convert(float,[c1_triple_holtwinters_multiplicative20]) as [c1_triple_holtwinters_multiplicative20]
										,convert(float,[c1_triple_holtwinters_multiplicative21]) as [c1_triple_holtwinters_multiplicative21]
										,convert(float,[c1_triple_holtwinters_multiplicative22]) as [c1_triple_holtwinters_multiplicative22]
										,convert(float,[c1_triple_holtwinters_multiplicative23]) as [c1_triple_holtwinters_multiplicative23]
										,convert(float,[c1_triple_holtwinters_multiplicative24]) as [c1_triple_holtwinters_multiplicative24]
										,convert(float,[c1_triple_holtwinters_multiplicative25]) as [c1_triple_holtwinters_multiplicative25]
										,convert(float,[c1_triple_holtwinters_multiplicative26]) as [c1_triple_holtwinters_multiplicative26]
										,convert(float,[c1_triple_holtwinters_multiplicative27]) as [c1_triple_holtwinters_multiplicative27]
										,convert(float,[c1_triple_holtwinters_multiplicative28]) as [c1_triple_holtwinters_multiplicative28]
										,convert(float,[c1_triple_holtwinters_multiplicative29]) as [c1_triple_holtwinters_multiplicative29]
										,convert(float,[c1_triple_holtwinters_multiplicative3]) as [c1_triple_holtwinters_multiplicative3]
										,convert(float,[c1_triple_holtwinters_multiplicative30]) as [c1_triple_holtwinters_multiplicative30]
										,convert(float,[c1_triple_holtwinters_multiplicative31]) as [c1_triple_holtwinters_multiplicative31]
										,convert(float,[c1_triple_holtwinters_multiplicative32]) as [c1_triple_holtwinters_multiplicative32]
										,convert(float,[c1_triple_holtwinters_multiplicative33]) as [c1_triple_holtwinters_multiplicative33]
										,convert(float,[c1_triple_holtwinters_multiplicative34]) as [c1_triple_holtwinters_multiplicative34]
										,convert(float,[c1_triple_holtwinters_multiplicative35]) as [c1_triple_holtwinters_multiplicative35]
										,convert(float,[c1_triple_holtwinters_multiplicative36]) as [c1_triple_holtwinters_multiplicative36]
										,convert(float,[c1_triple_holtwinters_multiplicative37]) as [c1_triple_holtwinters_multiplicative37]
										,convert(float,[c1_triple_holtwinters_multiplicative38]) as [c1_triple_holtwinters_multiplicative38]
										,convert(float,[c1_triple_holtwinters_multiplicative39]) as [c1_triple_holtwinters_multiplicative39]
										,convert(float,[c1_triple_holtwinters_multiplicative4]) as [c1_triple_holtwinters_multiplicative4]
										,convert(float,[c1_triple_holtwinters_multiplicative40]) as [c1_triple_holtwinters_multiplicative40]
										,convert(float,[c1_triple_holtwinters_multiplicative41]) as [c1_triple_holtwinters_multiplicative41]
										,convert(float,[c1_triple_holtwinters_multiplicative42]) as [c1_triple_holtwinters_multiplicative42]
										,convert(float,[c1_triple_holtwinters_multiplicative43]) as [c1_triple_holtwinters_multiplicative43]
										,convert(float,[c1_triple_holtwinters_multiplicative44]) as [c1_triple_holtwinters_multiplicative44]
										,convert(float,[c1_triple_holtwinters_multiplicative45]) as [c1_triple_holtwinters_multiplicative45]
										,convert(float,[c1_triple_holtwinters_multiplicative46]) as [c1_triple_holtwinters_multiplicative46]
										,convert(float,[c1_triple_holtwinters_multiplicative47]) as [c1_triple_holtwinters_multiplicative47]
										,convert(float,[c1_triple_holtwinters_multiplicative48]) as [c1_triple_holtwinters_multiplicative48]
										,convert(float,[c1_triple_holtwinters_multiplicative49]) as [c1_triple_holtwinters_multiplicative49]
										,convert(float,[c1_triple_holtwinters_multiplicative5]) as [c1_triple_holtwinters_multiplicative5]
										,convert(float,[c1_triple_holtwinters_multiplicative50]) as [c1_triple_holtwinters_multiplicative50]
										,convert(float,[c1_triple_holtwinters_multiplicative51]) as [c1_triple_holtwinters_multiplicative51]
										,convert(float,[c1_triple_holtwinters_multiplicative52]) as [c1_triple_holtwinters_multiplicative52]
										,convert(float,[c1_triple_holtwinters_multiplicative53]) as [c1_triple_holtwinters_multiplicative53]
										,convert(float,[c1_triple_holtwinters_multiplicative54]) as [c1_triple_holtwinters_multiplicative54]
										,convert(float,[c1_triple_holtwinters_multiplicative55]) as [c1_triple_holtwinters_multiplicative55]
										,convert(float,[c1_triple_holtwinters_multiplicative56]) as [c1_triple_holtwinters_multiplicative56]
										,convert(float,[c1_triple_holtwinters_multiplicative57]) as [c1_triple_holtwinters_multiplicative57]
										,convert(float,[c1_triple_holtwinters_multiplicative58]) as [c1_triple_holtwinters_multiplicative58]
										,convert(float,[c1_triple_holtwinters_multiplicative59]) as [c1_triple_holtwinters_multiplicative59]
										,convert(float,[c1_triple_holtwinters_multiplicative6]) as [c1_triple_holtwinters_multiplicative6]
										,convert(float,[c1_triple_holtwinters_multiplicative60]) as [c1_triple_holtwinters_multiplicative60]
										,convert(float,[c1_triple_holtwinters_multiplicative61]) as [c1_triple_holtwinters_multiplicative61]
										,convert(float,[c1_triple_holtwinters_multiplicative62]) as [c1_triple_holtwinters_multiplicative62]
										,convert(float,[c1_triple_holtwinters_multiplicative63]) as [c1_triple_holtwinters_multiplicative63]
										,convert(float,[c1_triple_holtwinters_multiplicative64]) as [c1_triple_holtwinters_multiplicative64]
										,convert(float,[c1_triple_holtwinters_multiplicative65]) as [c1_triple_holtwinters_multiplicative65]
										,convert(float,[c1_triple_holtwinters_multiplicative66]) as [c1_triple_holtwinters_multiplicative66]
										,convert(float,[c1_triple_holtwinters_multiplicative67]) as [c1_triple_holtwinters_multiplicative67]
										,convert(float,[c1_triple_holtwinters_multiplicative68]) as [c1_triple_holtwinters_multiplicative68]
										,convert(float,[c1_triple_holtwinters_multiplicative69]) as [c1_triple_holtwinters_multiplicative69]
										,convert(float,[c1_triple_holtwinters_multiplicative7]) as [c1_triple_holtwinters_multiplicative7]
										,convert(float,[c1_triple_holtwinters_multiplicative70]) as [c1_triple_holtwinters_multiplicative70]
										,convert(float,[c1_triple_holtwinters_multiplicative71]) as [c1_triple_holtwinters_multiplicative71]
										,convert(float,[c1_triple_holtwinters_multiplicative72]) as [c1_triple_holtwinters_multiplicative72]
										,convert(float,[c1_triple_holtwinters_multiplicative73]) as [c1_triple_holtwinters_multiplicative73]
										,convert(float,[c1_triple_holtwinters_multiplicative74]) as [c1_triple_holtwinters_multiplicative74]
										,convert(float,[c1_triple_holtwinters_multiplicative75]) as [c1_triple_holtwinters_multiplicative75]
										,convert(float,[c1_triple_holtwinters_multiplicative76]) as [c1_triple_holtwinters_multiplicative76]
										,convert(float,[c1_triple_holtwinters_multiplicative77]) as [c1_triple_holtwinters_multiplicative77]
										,convert(float,[c1_triple_holtwinters_multiplicative78]) as [c1_triple_holtwinters_multiplicative78]
											,convert(float,[c1_triple_holtwinters_multiplicative79]) as [c1_triple_holtwinters_multiplicative79]
										,convert(float,[c1_triple_holtwinters_multiplicative8]) as [c1_triple_holtwinters_multiplicative8]
										,convert(float,[c1_triple_holtwinters_multiplicative80]) as [c1_triple_holtwinters_multiplicative80]
										,convert(float,[c1_triple_holtwinters_multiplicative81]) as [c1_triple_holtwinters_multiplicative81]
										,convert(float,[c1_triple_holtwinters_multiplicative82]) as [c1_triple_holtwinters_multiplicative82]
										,convert(float,[c1_triple_holtwinters_multiplicative83]) as [c1_triple_holtwinters_multiplicative83]
										,convert(float,[c1_triple_holtwinters_multiplicative84]) as [c1_triple_holtwinters_multiplicative84]
										,convert(float,[c1_triple_holtwinters_multiplicative85]) as [c1_triple_holtwinters_multiplicative85]
										,convert(float,[c1_triple_holtwinters_multiplicative86]) as [c1_triple_holtwinters_multiplicative86]
										,convert(float,[c1_triple_holtwinters_multiplicative87]) as [c1_triple_holtwinters_multiplicative87]
										,convert(float,[c1_triple_holtwinters_multiplicative88]) as [c1_triple_holtwinters_multiplicative88]
										,convert(float,[c1_triple_holtwinters_multiplicative89]) as [c1_triple_holtwinters_multiplicative89]
										,convert(float,[c1_triple_holtwinters_multiplicative9]) as [c1_triple_holtwinters_multiplicative9]
										,convert(float,[c1_triple_holtwinters_multiplicative90]) as [c1_triple_holtwinters_multiplicative90]
										,convert(float,[c1_triple_holtwinters_multiplicative91]) as [c1_triple_holtwinters_multiplicative91]
										,convert(float,[c1_triple_holtwinters_multiplicative92]) as [c1_triple_holtwinters_multiplicative92]
										,convert(float,[c1_triple_holtwinters_multiplicative93]) as [c1_triple_holtwinters_multiplicative93]
										,convert(float,[c1_triple_holtwinters_multiplicative94]) as [c1_triple_holtwinters_multiplicative94]
										,convert(float,[c1_triple_holtwinters_multiplicative95]) as [c1_triple_holtwinters_multiplicative95]
										,convert(float,[c1_triple_holtwinters_multiplicative96]) as [c1_triple_holtwinters_multiplicative96]
										,convert(float,[c1_triple_holtwinters_multiplicative97]) as [c1_triple_holtwinters_multiplicative97]
										,convert(float,[c1_triple_holtwinters_multiplicative98]) as [c1_triple_holtwinters_multiplicative98]
										,convert(float,[c1_triple_holtwinters_multiplicative99]) as [c1_triple_holtwinters_multiplicative99]
									

	  into zzz_chris_final01
  FROM [NAO_PMO_Analytics].[dbo].[zzz_chris_final]

-------------------
DROP TABLE IF EXISTS [NAO_PMO_Analytics].[dbo].[zzz_final_forecast];  
select  t1.[Date]
      ,t1.[Scenario]
      ,t1.[Product]
      ,t1.[Sub-Product]
      ,t1.[m_Volumes] as Volumes
      ,[m_AutoRegressive_m]
      ,[m_MovingAverage]
      ,[m_AutoRegressive_MovingAverage]
      ,[m_AutoRegressive_Integrated_MovingAverage]
      ,[m1_Seasonal_AutoRegressive_Integrated_MovingAverage]
      ,[m2_Seasonal_AutoRegressive_Integrated_MovingAverage]
      ,[m3_Seasonal_AutoRegressive_Integrated_MovingAverage]
      ,[m4_Seasonal_AutoRegressive_Integrated_MovingAverage]
      ,[m5_Seasonal_AutoRegressive_Integrated_MovingAverage]
      ,[m_Holts_added_linear_trend]
      ,[m_Holts_added_damped_linear_trend]
      ,[m1_Holts_multiplicative_linear_trend]
      ,[m2_Holts_multiplicative_damped_linear_trend]
      ,[m3_Holts_added_linear_trend_with_seasonality]
      ,[m_Holts_added_dampened_linear_trend_with_seasonality]
      ,[m_Holts_multiplicative_linear_trend_with_seasonality]
      ,[m_Holts_multiplicative_dampened_linear_trend_with_seasonality]
      ,[m1_Holts_tunned_model_m1]
      ,[m2_Holts_tunned_model_m1]
      ,[m3_Holts_tunned_model_m1]
      ,[m_Simple_Exponential_Smoothing_m]
      ,[m1_Error_trend_seasonality_tunned]
      ,[m2_Error_trend_seasonality_tunned]
      ,[m3_Error_trend_seasonality_tunned]
      ,[m1_NN]
      ,[m1_LSTM]
      ,[m2_NN]
      ,[m2_CNN]
      ,[m2_LSTM]
      ,[m3_NN]
      ,[m3_CNN]
      ,[m3_LSTM]
      ,[m4_NN]
      ,[m4_CNN]
      ,[m4_LSTM]
      ,[m4_LSTM_CNN]
      ,[m_Prophet]
      ,[m_GPY]
      ,[m_Regression_Tree]
      ,[m_Random_forest]
	  ,[c1_AAA_ets]
      ,[c1_AAN_ets]
      ,[c1_add_holtlineartrend]
      ,[c1_add_holtlineartrenddamp]
      ,[c1_ANA_ets]
      ,[c1_autoregressive_integratedmovingaverage]
      ,[c1_autoregressive_integratedmovingaverage_1]
      ,[c1_autoregressive_integratedmovingaverage_2]
      ,[c1_autoregressive_integratedmovingaverage_3]
      ,[c1_autoregressive_integratedmovingaverage_4]
      ,[c1_autoregressive_integratedmovingaverage_5]
      ,[c1_boxcoxtransform_armaerrors_trend_seasonal]
      ,[c1_cubicspline1]
      ,[c1_cubicspline2]
      ,[c1_double_holt_additive]
      ,[c1_dynamicharmonicregression]
      ,[c1_linearmodel_seasontrend]
      ,[c1_linearmodel_trend]
      ,[c1_MAA_ets]
      ,[c1_MAM_ets]
      ,[c1_MAN_ets]
      ,[c1_MMM_ets]
      ,[c1_MMN_ets]
      ,[c1_MNA_ets]
      ,[c1_MNM_ets]
      ,[c1_sarima1]
      ,[c1_sarima10]
      ,[c1_sarima11]
      ,[c1_sarima12]
      ,[c1_sarima13]
      ,[c1_sarima14]
      ,[c1_sarima15]
      ,[c1_sarima16]
      ,[c1_sarima17]
      ,[c1_sarima18]
      ,[c1_sarima19]
      ,[c1_sarima2]
      ,[c1_sarima20]
      ,[c1_sarima21]
      ,[c1_sarima22]
      ,[c1_sarima23]
      ,[c1_sarima24]
      ,[c1_sarima25]
      ,[c1_sarima26]
      ,[c1_sarima27]
      ,[c1_sarima28]
      ,[c1_sarima29]
      ,[c1_sarima3]
      ,[c1_sarima30]
      ,[c1_sarima31]
      ,[c1_sarima32]
      ,[c1_sarima33]
      ,[c1_sarima34]
      ,[c1_sarima35]
      ,[c1_sarima36]
      ,[c1_sarima37]
      ,[c1_sarima38]
      ,[c1_sarima39]
      ,[c1_sarima4]
      ,[c1_sarima40]
      ,[c1_sarima41]
      ,[c1_sarima42]
      ,[c1_sarima43]
      ,[c1_sarima44]
      ,[c1_sarima45]
      ,[c1_sarima46]
      ,[c1_sarima47]
      ,[c1_sarima48]
      ,[c1_sarima49]
      ,[c1_sarima5]
      ,[c1_sarima50]
      ,[c1_sarima51]
      ,[c1_sarima52]
      ,[c1_sarima53]
      ,[c1_sarima54]
      ,[c1_sarima55]
      ,[c1_sarima56]
      ,[c1_sarima57]
      ,[c1_sarima58]
      ,[c1_sarima59]
      ,[c1_sarima6]
      ,[c1_sarima60]
      ,[c1_sarima61]
      ,[c1_sarima62]
      ,[c1_sarima63]
      ,[c1_sarima64]
      ,[c1_sarima65]
      ,[c1_sarima66]
      ,[c1_sarima67]
      ,[c1_sarima68]
      ,[c1_sarima69]
      ,[c1_sarima7]
      ,[c1_sarima70]
      ,[c1_sarima71]
      ,[c1_sarima72]
      ,[c1_sarima73]
      ,[c1_sarima74]
      ,[c1_sarima75]
      ,[c1_sarima76]
      ,[c1_sarima77]
      ,[c1_sarima8]
      ,[c1_sarima9]
      ,[c1_simple_expo_smooth0]
      --,[c1_triple_holtwinters_additive0]
      ,[c1_triple_holtwinters_additive1]
      ,[c1_triple_holtwinters_additive10]
      ,[c1_triple_holtwinters_additive100]
      ,[c1_triple_holtwinters_additive11]
      ,[c1_triple_holtwinters_additive12]
      ,[c1_triple_holtwinters_additive13]
      ,[c1_triple_holtwinters_additive14]
      ,[c1_triple_holtwinters_additive15]
      ,[c1_triple_holtwinters_additive16]
      ,[c1_triple_holtwinters_additive17]
      ,[c1_triple_holtwinters_additive18]
      ,[c1_triple_holtwinters_additive19]
      ,[c1_triple_holtwinters_additive2]
      ,[c1_triple_holtwinters_additive20]
      ,[c1_triple_holtwinters_additive21]
      ,[c1_triple_holtwinters_additive22]
      ,[c1_triple_holtwinters_additive23]
      ,[c1_triple_holtwinters_additive24]
      ,[c1_triple_holtwinters_additive25]
      ,[c1_triple_holtwinters_additive26]
      ,[c1_triple_holtwinters_additive27]
      ,[c1_triple_holtwinters_additive28]
      ,[c1_triple_holtwinters_additive29]
      ,[c1_triple_holtwinters_additive3]
      ,[c1_triple_holtwinters_additive30]
      ,[c1_triple_holtwinters_additive31]
      ,[c1_triple_holtwinters_additive32]
      ,[c1_triple_holtwinters_additive33]
      ,[c1_triple_holtwinters_additive34]
      ,[c1_triple_holtwinters_additive35]
      ,[c1_triple_holtwinters_additive36]
      ,[c1_triple_holtwinters_additive37]
      ,[c1_triple_holtwinters_additive38]
      ,[c1_triple_holtwinters_additive39]
      ,[c1_triple_holtwinters_additive4]
      ,[c1_triple_holtwinters_additive40]
      ,[c1_triple_holtwinters_additive41]
      ,[c1_triple_holtwinters_additive42]
      ,[c1_triple_holtwinters_additive43]
      ,[c1_triple_holtwinters_additive44]
      ,[c1_triple_holtwinters_additive45]
      ,[c1_triple_holtwinters_additive46]
      ,[c1_triple_holtwinters_additive47]
      ,[c1_triple_holtwinters_additive48]
      ,[c1_triple_holtwinters_additive49]
      ,[c1_triple_holtwinters_additive5]
      ,[c1_triple_holtwinters_additive50]
      ,[c1_triple_holtwinters_additive51]
      ,[c1_triple_holtwinters_additive52]
      ,[c1_triple_holtwinters_additive53]
      ,[c1_triple_holtwinters_additive54]
      ,[c1_triple_holtwinters_additive55]
      ,[c1_triple_holtwinters_additive56]
      ,[c1_triple_holtwinters_additive57]
      ,[c1_triple_holtwinters_additive58]
      ,[c1_triple_holtwinters_additive59]
      ,[c1_triple_holtwinters_additive6]
      ,[c1_triple_holtwinters_additive60]
      ,[c1_triple_holtwinters_additive61]
      ,[c1_triple_holtwinters_additive62]
      ,[c1_triple_holtwinters_additive63]
      ,[c1_triple_holtwinters_additive64]
      ,[c1_triple_holtwinters_additive65]
      ,[c1_triple_holtwinters_additive66]
      ,[c1_triple_holtwinters_additive67]
      ,[c1_triple_holtwinters_additive68]
      ,[c1_triple_holtwinters_additive69]
      ,[c1_triple_holtwinters_additive7]
      ,[c1_triple_holtwinters_additive70]
      ,[c1_triple_holtwinters_additive71]
      ,[c1_triple_holtwinters_additive72]
      ,[c1_triple_holtwinters_additive73]
      ,[c1_triple_holtwinters_additive74]
      ,[c1_triple_holtwinters_additive75]
      ,[c1_triple_holtwinters_additive76]
      ,[c1_triple_holtwinters_additive77]
      ,[c1_triple_holtwinters_additive78]
      ,[c1_triple_holtwinters_additive79]
      ,[c1_triple_holtwinters_additive8]
      ,[c1_triple_holtwinters_additive80]
      ,[c1_triple_holtwinters_additive81]
      ,[c1_triple_holtwinters_additive82]
      ,[c1_triple_holtwinters_additive83]
      ,[c1_triple_holtwinters_additive84]
      ,[c1_triple_holtwinters_additive85]
      ,[c1_triple_holtwinters_additive86]
      ,[c1_triple_holtwinters_additive87]
      ,[c1_triple_holtwinters_additive88]
      ,[c1_triple_holtwinters_additive89]
      ,[c1_triple_holtwinters_additive9]
      ,[c1_triple_holtwinters_additive90]
      ,[c1_triple_holtwinters_additive91]
      ,[c1_triple_holtwinters_additive92]
      ,[c1_triple_holtwinters_additive93]
      ,[c1_triple_holtwinters_additive94]
      ,[c1_triple_holtwinters_additive95]
      ,[c1_triple_holtwinters_additive96]
      ,[c1_triple_holtwinters_additive97]
      ,[c1_triple_holtwinters_additive98]
      ,[c1_triple_holtwinters_additive99]
      ,[c1_triple_holtwinters_multiplicative0]
      ,[c1_triple_holtwinters_multiplicative1]
      ,[c1_triple_holtwinters_multiplicative10]
      ,[c1_triple_holtwinters_multiplicative100]
      ,[c1_triple_holtwinters_multiplicative11]
      ,[c1_triple_holtwinters_multiplicative12]
      ,[c1_triple_holtwinters_multiplicative13]
      ,[c1_triple_holtwinters_multiplicative14]
      ,[c1_triple_holtwinters_multiplicative15]
      ,[c1_triple_holtwinters_multiplicative16]
      ,[c1_triple_holtwinters_multiplicative17]
      ,[c1_triple_holtwinters_multiplicative18]
      ,[c1_triple_holtwinters_multiplicative19]
      ,[c1_triple_holtwinters_multiplicative2]
      ,[c1_triple_holtwinters_multiplicative20]
      ,[c1_triple_holtwinters_multiplicative21]
      ,[c1_triple_holtwinters_multiplicative22]
      ,[c1_triple_holtwinters_multiplicative23]
      ,[c1_triple_holtwinters_multiplicative24]
      ,[c1_triple_holtwinters_multiplicative25]
      ,[c1_triple_holtwinters_multiplicative26]
      ,[c1_triple_holtwinters_multiplicative27]
      ,[c1_triple_holtwinters_multiplicative28]
      ,[c1_triple_holtwinters_multiplicative29]
      ,[c1_triple_holtwinters_multiplicative3]
      ,[c1_triple_holtwinters_multiplicative30]
      ,[c1_triple_holtwinters_multiplicative31]
      ,[c1_triple_holtwinters_multiplicative32]
      ,[c1_triple_holtwinters_multiplicative33]
      ,[c1_triple_holtwinters_multiplicative34]
      ,[c1_triple_holtwinters_multiplicative35]
      ,[c1_triple_holtwinters_multiplicative36]
      ,[c1_triple_holtwinters_multiplicative37]
      ,[c1_triple_holtwinters_multiplicative38]
      ,[c1_triple_holtwinters_multiplicative39]
      ,[c1_triple_holtwinters_multiplicative4]
      ,[c1_triple_holtwinters_multiplicative40]
      ,[c1_triple_holtwinters_multiplicative41]
      ,[c1_triple_holtwinters_multiplicative42]
      ,[c1_triple_holtwinters_multiplicative43]
      ,[c1_triple_holtwinters_multiplicative44]
      ,[c1_triple_holtwinters_multiplicative45]
      ,[c1_triple_holtwinters_multiplicative46]
      ,[c1_triple_holtwinters_multiplicative47]
      ,[c1_triple_holtwinters_multiplicative48]
      ,[c1_triple_holtwinters_multiplicative49]
      ,[c1_triple_holtwinters_multiplicative5]
      ,[c1_triple_holtwinters_multiplicative50]
      ,[c1_triple_holtwinters_multiplicative51]
      ,[c1_triple_holtwinters_multiplicative52]
      ,[c1_triple_holtwinters_multiplicative53]
      ,[c1_triple_holtwinters_multiplicative54]
      ,[c1_triple_holtwinters_multiplicative55]
      ,[c1_triple_holtwinters_multiplicative56]
      ,[c1_triple_holtwinters_multiplicative57]
      ,[c1_triple_holtwinters_multiplicative58]
      ,[c1_triple_holtwinters_multiplicative59]
      ,[c1_triple_holtwinters_multiplicative6]
      ,[c1_triple_holtwinters_multiplicative60]
      ,[c1_triple_holtwinters_multiplicative61]
      ,[c1_triple_holtwinters_multiplicative62]
      ,[c1_triple_holtwinters_multiplicative63]
      ,[c1_triple_holtwinters_multiplicative64]
      ,[c1_triple_holtwinters_multiplicative65]
      ,[c1_triple_holtwinters_multiplicative66]
      ,[c1_triple_holtwinters_multiplicative67]
      ,[c1_triple_holtwinters_multiplicative68]
      ,[c1_triple_holtwinters_multiplicative69]
      ,[c1_triple_holtwinters_multiplicative7]
      ,[c1_triple_holtwinters_multiplicative70]
      ,[c1_triple_holtwinters_multiplicative71]
      ,[c1_triple_holtwinters_multiplicative72]
      ,[c1_triple_holtwinters_multiplicative73]
      ,[c1_triple_holtwinters_multiplicative74]
      ,[c1_triple_holtwinters_multiplicative75]
      ,[c1_triple_holtwinters_multiplicative76]
      ,[c1_triple_holtwinters_multiplicative77]
      ,[c1_triple_holtwinters_multiplicative78]
      ,[c1_triple_holtwinters_multiplicative79]
      ,[c1_triple_holtwinters_multiplicative8]
      ,[c1_triple_holtwinters_multiplicative80]
      ,[c1_triple_holtwinters_multiplicative81]
      ,[c1_triple_holtwinters_multiplicative82]
      ,[c1_triple_holtwinters_multiplicative83]
      ,[c1_triple_holtwinters_multiplicative84]
      ,[c1_triple_holtwinters_multiplicative85]
      ,[c1_triple_holtwinters_multiplicative86]
      ,[c1_triple_holtwinters_multiplicative87]
      ,[c1_triple_holtwinters_multiplicative88]
      ,[c1_triple_holtwinters_multiplicative89]
      ,[c1_triple_holtwinters_multiplicative9]
      ,[c1_triple_holtwinters_multiplicative90]
      ,[c1_triple_holtwinters_multiplicative91]
      ,[c1_triple_holtwinters_multiplicative92]
      ,[c1_triple_holtwinters_multiplicative93]
      ,[c1_triple_holtwinters_multiplicative94]
      ,[c1_triple_holtwinters_multiplicative95]
      ,[c1_triple_holtwinters_multiplicative96]
      ,[c1_triple_holtwinters_multiplicative97]
      ,[c1_triple_holtwinters_multiplicative98]
      ,[c1_triple_holtwinters_multiplicative99]
	  into [NAO_PMO_Analytics].[dbo].[zzz_final_forecast]
from [NAO_PMO_Analytics].[dbo].[zzz_mithun_forecast01] t1 join [NAO_PMO_Analytics].[dbo].[zzz_chris_final01] t2 on t1.[Date]=t2.[date] and t1.[Product]=t2.[product] and t1.[Sub-Product]=t2.[Sub.Product] and t1.[m_Volumes]=t2.[Volumes] and t1.[Scenario]=t2.[Scenario]; 



DROP TABLE IF EXISTS [NAO_PMO_Analytics].[dbo].[zzz_final_unpvt];  
select Primary_key = ROW_NUMBER() OVER (ORDER BY[Volumes]),
[date],[Scenario],[Product], [Sub-Product],
	  [Volumes], Methods, Forecasting 
	  into [NAO_PMO_Analytics].[dbo].zzz_final_unpvt
	  from [NAO_PMO_Analytics].[dbo].[zzz_final_forecast]
	  unpivot(
	  Forecasting
	  for Methods in ([m_AutoRegressive_m]
      ,[m_MovingAverage]
      ,[m_AutoRegressive_MovingAverage]
      ,[m_AutoRegressive_Integrated_MovingAverage]
      ,[m1_Seasonal_AutoRegressive_Integrated_MovingAverage]
      ,[m2_Seasonal_AutoRegressive_Integrated_MovingAverage]
      ,[m3_Seasonal_AutoRegressive_Integrated_MovingAverage]
      ,[m4_Seasonal_AutoRegressive_Integrated_MovingAverage]
      ,[m5_Seasonal_AutoRegressive_Integrated_MovingAverage]
      ,[m_Holts_added_linear_trend]
      ,[m_Holts_added_damped_linear_trend]
      ,[m1_Holts_multiplicative_linear_trend]
      ,[m2_Holts_multiplicative_damped_linear_trend]
      ,[m3_Holts_added_linear_trend_with_seasonality]
      ,[m_Holts_added_dampened_linear_trend_with_seasonality]
      ,[m_Holts_multiplicative_linear_trend_with_seasonality]
      ,[m_Holts_multiplicative_dampened_linear_trend_with_seasonality]
      ,[m1_Holts_tunned_model_m1]
      ,[m2_Holts_tunned_model_m1]
      ,[m3_Holts_tunned_model_m1]
      ,[m_Simple_Exponential_Smoothing_m]
      ,[m1_Error_trend_seasonality_tunned]
      ,[m2_Error_trend_seasonality_tunned]
      ,[m3_Error_trend_seasonality_tunned]
      ,[m1_NN]
      ,[m1_LSTM]
      ,[m2_NN]
      ,[m2_CNN]
      ,[m2_LSTM]
      ,[m3_NN]
      ,[m3_CNN]
      ,[m3_LSTM]
      ,[m4_NN]
      ,[m4_CNN]
      ,[m4_LSTM]
      ,[m4_LSTM_CNN]
      ,[m_Prophet]
      ,[m_GPY]
      ,[m_Regression_Tree]
      ,[m_Random_forest]
	  ,[c1_AAA_ets]
      ,[c1_AAN_ets]
      ,[c1_add_holtlineartrend]
      ,[c1_add_holtlineartrenddamp]
      ,[c1_ANA_ets]
      ,[c1_autoregressive_integratedmovingaverage]
      ,[c1_autoregressive_integratedmovingaverage_1]
      ,[c1_autoregressive_integratedmovingaverage_2]
      ,[c1_autoregressive_integratedmovingaverage_3]
      ,[c1_autoregressive_integratedmovingaverage_4]
      ,[c1_autoregressive_integratedmovingaverage_5]
      ,[c1_boxcoxtransform_armaerrors_trend_seasonal]
      ,[c1_cubicspline1]
      ,[c1_cubicspline2]
      ,[c1_double_holt_additive]
      ,[c1_dynamicharmonicregression]
      ,[c1_linearmodel_seasontrend]
      ,[c1_linearmodel_trend]
      ,[c1_MAA_ets]
      ,[c1_MAM_ets]
      ,[c1_MAN_ets]
      ,[c1_MMM_ets]
      ,[c1_MMN_ets]
      ,[c1_MNA_ets]
      ,[c1_MNM_ets]
      ,[c1_sarima1]
      ,[c1_sarima10]
      ,[c1_sarima11]
      ,[c1_sarima12]
      ,[c1_sarima13]
      ,[c1_sarima14]
      ,[c1_sarima15]
      ,[c1_sarima16]
      ,[c1_sarima17]
      ,[c1_sarima18]
      ,[c1_sarima19]
      ,[c1_sarima2]
      ,[c1_sarima20]
      ,[c1_sarima21]
      ,[c1_sarima22]
      ,[c1_sarima23]
      ,[c1_sarima24]
      ,[c1_sarima25]
      ,[c1_sarima26]
      ,[c1_sarima27]
      ,[c1_sarima28]
      ,[c1_sarima29]
      ,[c1_sarima3]
      ,[c1_sarima30]
      ,[c1_sarima31]
      ,[c1_sarima32]
      ,[c1_sarima33]
      ,[c1_sarima34]
      ,[c1_sarima35]
      ,[c1_sarima36]
      ,[c1_sarima37]
      ,[c1_sarima38]
      ,[c1_sarima39]
      ,[c1_sarima4]
      ,[c1_sarima40]
      ,[c1_sarima41]
      ,[c1_sarima42]
      ,[c1_sarima43]
      ,[c1_sarima44]
      ,[c1_sarima45]
      ,[c1_sarima46]
      ,[c1_sarima47]
      ,[c1_sarima48]
      ,[c1_sarima49]
      ,[c1_sarima5]
      ,[c1_sarima50]
      ,[c1_sarima51]
      ,[c1_sarima52]
      ,[c1_sarima53]
      ,[c1_sarima54]
      ,[c1_sarima55]
      ,[c1_sarima56]
      ,[c1_sarima57]
      ,[c1_sarima58]
      ,[c1_sarima59]
      ,[c1_sarima6]
      ,[c1_sarima60]
      ,[c1_sarima61]
      ,[c1_sarima62]
      ,[c1_sarima63]
      ,[c1_sarima64]
      ,[c1_sarima65]
      ,[c1_sarima66]
      ,[c1_sarima67]
      ,[c1_sarima68]
      ,[c1_sarima69]
      ,[c1_sarima7]
      ,[c1_sarima70]
      ,[c1_sarima71]
      ,[c1_sarima72]
      ,[c1_sarima73]
      ,[c1_sarima74]
      ,[c1_sarima75]
      ,[c1_sarima76]
      ,[c1_sarima77]
      ,[c1_sarima8]
      ,[c1_sarima9]
      ,[c1_simple_expo_smooth0]
      --,[c1_triple_holtwinters_additive0]
      ,[c1_triple_holtwinters_additive1]
      ,[c1_triple_holtwinters_additive10]
      ,[c1_triple_holtwinters_additive100]
      ,[c1_triple_holtwinters_additive11]
      ,[c1_triple_holtwinters_additive12]
      ,[c1_triple_holtwinters_additive13]
      ,[c1_triple_holtwinters_additive14]
      ,[c1_triple_holtwinters_additive15]
      ,[c1_triple_holtwinters_additive16]
      ,[c1_triple_holtwinters_additive17]
      ,[c1_triple_holtwinters_additive18]
      ,[c1_triple_holtwinters_additive19]
      ,[c1_triple_holtwinters_additive2]
      ,[c1_triple_holtwinters_additive20]
      ,[c1_triple_holtwinters_additive21]
      ,[c1_triple_holtwinters_additive22]
      ,[c1_triple_holtwinters_additive23]
      ,[c1_triple_holtwinters_additive24]
      ,[c1_triple_holtwinters_additive25]
      ,[c1_triple_holtwinters_additive26]
      ,[c1_triple_holtwinters_additive27]
      ,[c1_triple_holtwinters_additive28]
      ,[c1_triple_holtwinters_additive29]
      ,[c1_triple_holtwinters_additive3]
      ,[c1_triple_holtwinters_additive30]
      ,[c1_triple_holtwinters_additive31]
      ,[c1_triple_holtwinters_additive32]
      ,[c1_triple_holtwinters_additive33]
      ,[c1_triple_holtwinters_additive34]
      ,[c1_triple_holtwinters_additive35]
      ,[c1_triple_holtwinters_additive36]
      ,[c1_triple_holtwinters_additive37]
      ,[c1_triple_holtwinters_additive38]
      ,[c1_triple_holtwinters_additive39]
      ,[c1_triple_holtwinters_additive4]
      ,[c1_triple_holtwinters_additive40]
      ,[c1_triple_holtwinters_additive41]
      ,[c1_triple_holtwinters_additive42]
      ,[c1_triple_holtwinters_additive43]
      ,[c1_triple_holtwinters_additive44]
      ,[c1_triple_holtwinters_additive45]
      ,[c1_triple_holtwinters_additive46]
      ,[c1_triple_holtwinters_additive47]
      ,[c1_triple_holtwinters_additive48]
      ,[c1_triple_holtwinters_additive49]
      ,[c1_triple_holtwinters_additive5]
      ,[c1_triple_holtwinters_additive50]
      ,[c1_triple_holtwinters_additive51]
      ,[c1_triple_holtwinters_additive52]
      ,[c1_triple_holtwinters_additive53]
      ,[c1_triple_holtwinters_additive54]
      ,[c1_triple_holtwinters_additive55]
      ,[c1_triple_holtwinters_additive56]
      ,[c1_triple_holtwinters_additive57]
      ,[c1_triple_holtwinters_additive58]
      ,[c1_triple_holtwinters_additive59]
      ,[c1_triple_holtwinters_additive6]
      ,[c1_triple_holtwinters_additive60]
      ,[c1_triple_holtwinters_additive61]
      ,[c1_triple_holtwinters_additive62]
      ,[c1_triple_holtwinters_additive63]
      ,[c1_triple_holtwinters_additive64]
      ,[c1_triple_holtwinters_additive65]
      ,[c1_triple_holtwinters_additive66]
      ,[c1_triple_holtwinters_additive67]
      ,[c1_triple_holtwinters_additive68]
      ,[c1_triple_holtwinters_additive69]
      ,[c1_triple_holtwinters_additive7]
      ,[c1_triple_holtwinters_additive70]
      ,[c1_triple_holtwinters_additive71]
      ,[c1_triple_holtwinters_additive72]
      ,[c1_triple_holtwinters_additive73]
      ,[c1_triple_holtwinters_additive74]
      ,[c1_triple_holtwinters_additive75]
      ,[c1_triple_holtwinters_additive76]
      ,[c1_triple_holtwinters_additive77]
      ,[c1_triple_holtwinters_additive78]
      ,[c1_triple_holtwinters_additive79]
      ,[c1_triple_holtwinters_additive8]
      ,[c1_triple_holtwinters_additive80]
      ,[c1_triple_holtwinters_additive81]
      ,[c1_triple_holtwinters_additive82]
      ,[c1_triple_holtwinters_additive83]
      ,[c1_triple_holtwinters_additive84]
      ,[c1_triple_holtwinters_additive85]
      ,[c1_triple_holtwinters_additive86]
      ,[c1_triple_holtwinters_additive87]
      ,[c1_triple_holtwinters_additive88]
      ,[c1_triple_holtwinters_additive89]
      ,[c1_triple_holtwinters_additive9]
      ,[c1_triple_holtwinters_additive90]
      ,[c1_triple_holtwinters_additive91]
      ,[c1_triple_holtwinters_additive92]
      ,[c1_triple_holtwinters_additive93]
      ,[c1_triple_holtwinters_additive94]
      ,[c1_triple_holtwinters_additive95]
      ,[c1_triple_holtwinters_additive96]
      ,[c1_triple_holtwinters_additive97]
      ,[c1_triple_holtwinters_additive98]
      ,[c1_triple_holtwinters_additive99]
      ,[c1_triple_holtwinters_multiplicative0]
      ,[c1_triple_holtwinters_multiplicative1]
      ,[c1_triple_holtwinters_multiplicative10]
      ,[c1_triple_holtwinters_multiplicative100]
      ,[c1_triple_holtwinters_multiplicative11]
      ,[c1_triple_holtwinters_multiplicative12]
      ,[c1_triple_holtwinters_multiplicative13]
      ,[c1_triple_holtwinters_multiplicative14]
      ,[c1_triple_holtwinters_multiplicative15]
      ,[c1_triple_holtwinters_multiplicative16]
      ,[c1_triple_holtwinters_multiplicative17]
      ,[c1_triple_holtwinters_multiplicative18]
      ,[c1_triple_holtwinters_multiplicative19]
      ,[c1_triple_holtwinters_multiplicative2]
      ,[c1_triple_holtwinters_multiplicative20]
      ,[c1_triple_holtwinters_multiplicative21]
      ,[c1_triple_holtwinters_multiplicative22]
      ,[c1_triple_holtwinters_multiplicative23]
      ,[c1_triple_holtwinters_multiplicative24]
      ,[c1_triple_holtwinters_multiplicative25]
      ,[c1_triple_holtwinters_multiplicative26]
      ,[c1_triple_holtwinters_multiplicative27]
      ,[c1_triple_holtwinters_multiplicative28]
      ,[c1_triple_holtwinters_multiplicative29]
      ,[c1_triple_holtwinters_multiplicative3]
      ,[c1_triple_holtwinters_multiplicative30]
      ,[c1_triple_holtwinters_multiplicative31]
      ,[c1_triple_holtwinters_multiplicative32]
      ,[c1_triple_holtwinters_multiplicative33]
      ,[c1_triple_holtwinters_multiplicative34]
      ,[c1_triple_holtwinters_multiplicative35]
      ,[c1_triple_holtwinters_multiplicative36]
      ,[c1_triple_holtwinters_multiplicative37]
      ,[c1_triple_holtwinters_multiplicative38]
      ,[c1_triple_holtwinters_multiplicative39]
      ,[c1_triple_holtwinters_multiplicative4]
      ,[c1_triple_holtwinters_multiplicative40]
      ,[c1_triple_holtwinters_multiplicative41]
      ,[c1_triple_holtwinters_multiplicative42]
      ,[c1_triple_holtwinters_multiplicative43]
      ,[c1_triple_holtwinters_multiplicative44]
      ,[c1_triple_holtwinters_multiplicative45]
      ,[c1_triple_holtwinters_multiplicative46]
      ,[c1_triple_holtwinters_multiplicative47]
      ,[c1_triple_holtwinters_multiplicative48]
      ,[c1_triple_holtwinters_multiplicative49]
      ,[c1_triple_holtwinters_multiplicative5]
      ,[c1_triple_holtwinters_multiplicative50]
      ,[c1_triple_holtwinters_multiplicative51]
      ,[c1_triple_holtwinters_multiplicative52]
      ,[c1_triple_holtwinters_multiplicative53]
      ,[c1_triple_holtwinters_multiplicative54]
      ,[c1_triple_holtwinters_multiplicative55]
      ,[c1_triple_holtwinters_multiplicative56]
      ,[c1_triple_holtwinters_multiplicative57]
      ,[c1_triple_holtwinters_multiplicative58]
      ,[c1_triple_holtwinters_multiplicative59]
      ,[c1_triple_holtwinters_multiplicative6]
      ,[c1_triple_holtwinters_multiplicative60]
      ,[c1_triple_holtwinters_multiplicative61]
      ,[c1_triple_holtwinters_multiplicative62]
      ,[c1_triple_holtwinters_multiplicative63]
      ,[c1_triple_holtwinters_multiplicative64]
      ,[c1_triple_holtwinters_multiplicative65]
      ,[c1_triple_holtwinters_multiplicative66]
      ,[c1_triple_holtwinters_multiplicative67]
      ,[c1_triple_holtwinters_multiplicative68]
      ,[c1_triple_holtwinters_multiplicative69]
      ,[c1_triple_holtwinters_multiplicative7]
      ,[c1_triple_holtwinters_multiplicative70]
      ,[c1_triple_holtwinters_multiplicative71]
      ,[c1_triple_holtwinters_multiplicative72]
      ,[c1_triple_holtwinters_multiplicative73]
      ,[c1_triple_holtwinters_multiplicative74]
      ,[c1_triple_holtwinters_multiplicative75]
      ,[c1_triple_holtwinters_multiplicative76]
      ,[c1_triple_holtwinters_multiplicative77]
      ,[c1_triple_holtwinters_multiplicative78]
      ,[c1_triple_holtwinters_multiplicative79]
      ,[c1_triple_holtwinters_multiplicative8]
      ,[c1_triple_holtwinters_multiplicative80]
      ,[c1_triple_holtwinters_multiplicative81]
      ,[c1_triple_holtwinters_multiplicative82]
      ,[c1_triple_holtwinters_multiplicative83]
      ,[c1_triple_holtwinters_multiplicative84]
      ,[c1_triple_holtwinters_multiplicative85]
      ,[c1_triple_holtwinters_multiplicative86]
      ,[c1_triple_holtwinters_multiplicative87]
      ,[c1_triple_holtwinters_multiplicative88]
      ,[c1_triple_holtwinters_multiplicative89]
      ,[c1_triple_holtwinters_multiplicative9]
      ,[c1_triple_holtwinters_multiplicative90]
      ,[c1_triple_holtwinters_multiplicative91]
      ,[c1_triple_holtwinters_multiplicative92]
      ,[c1_triple_holtwinters_multiplicative93]
      ,[c1_triple_holtwinters_multiplicative94]
      ,[c1_triple_holtwinters_multiplicative95]
      ,[c1_triple_holtwinters_multiplicative96]
      ,[c1_triple_holtwinters_multiplicative97]
      ,[c1_triple_holtwinters_multiplicative98]
      ,[c1_triple_holtwinters_multiplicative99]
	  )) as unpiv;
